# Generated by Django 4.2.4 on 2023-08-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSUnsafeTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50)),
                ('trackfile', models.CharField(max_length=50)),
                ('clip', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('GFIStartFrame', models.IntegerField()),
                ('GFIEndFrame', models.IntegerField()),
                ('root_cause', models.CharField(max_length=50)),
                ('longitudinal_speed', models.FloatField()),
                ('lateral_speed', models.FloatField()),
                ('ego_motion_path_offset', models.FloatField()),
                ('closest_by_ego_motion_path', models.FloatField()),
                ('longitudinal_distance', models.FloatField()),
                ('lateral_distance', models.FloatField()),
                ('rss_safe', models.BooleanField()),
                ('rss_longitudinal_score', models.FloatField()),
                ('rss_lateral_score', models.FloatField()),
                ('em_path_heading', models.FloatField()),
                ('heading_vs_em_path', models.FloatField()),
                ('em_vt', models.FloatField()),
                ('vt_towards_em_path', models.FloatField()),
                ('em_vm', models.FloatField()),
                ('em_m', models.FloatField()),
                ('em_abs_t', models.FloatField()),
                ('em_signed_t', models.FloatField()),
                ('em_perc_of_seg', models.FloatField()),
                ('min_proj_dist_to_em_seg_edge', models.FloatField()),
                ('added_cutin_path', models.BooleanField()),
                ('rss_lat_safe', models.BooleanField()),
                ('current_rss_lat_safe', models.BooleanField()),
                ('safe_lat_dist', models.FloatField()),
                ('t_braking_dist_lat_brake', models.FloatField()),
                ('em_t_at_lateral_brake_lat', models.FloatField()),
                ('lat_brake_rss_lat_safe', models.BooleanField()),
                ('rss_lat_safe_lat_brake', models.BooleanField()),
                ('speed_based_heading', models.FloatField()),
                ('current_rss_lat_score', models.FloatField()),
                ('lat_brake_rss_lat_score', models.FloatField()),
                ('current_rss_lat_diff', models.FloatField()),
                ('lat_brake_rss_lat_diff', models.FloatField()),
                ('control_on', models.BooleanField()),
            ],
        ),
    ]
