# Generated by Django 4.2.4 on 2023-08-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssunsafetemp',
            name='closest_by_ego_motion_path',
            field=models.BooleanField(),
        ),
    ]
