# Generated by Django 4.2.4 on 2023-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hil_app', '0002_alter_rssunsafetemp_closest_by_ego_motion_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssunsafetemp',
            name='control_on',
            field=models.FloatField(),
        ),
    ]
