# Generated by Django 4.2.4 on 2023-08-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hil_app', '0003_alter_rssunsafetemp_control_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.CharField(max_length=50, unique=True)),
                ('drive_name', models.CharField(max_length=50)),
                ('time_of_day', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('road_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gfi', models.IntegerField()),
                ('grab_index', models.IntegerField()),
                ('ego_speed', models.FloatField()),
                ('yaw_rate', models.FloatField()),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hil_app.clip', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50, unique=True)),
                ('version_date', models.DateTimeField()),
                ('version_description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSSUnsafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackfile', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('root_cause', models.CharField(max_length=50)),
                ('longitudinal_speed', models.FloatField()),
                ('lateral_speed', models.FloatField()),
                ('ego_motion_path_offset', models.FloatField()),
                ('closest_by_ego_motion_path', models.BooleanField()),
                ('longitudinal_distance', models.FloatField()),
                ('lateral_distance', models.FloatField()),
                ('rss_safe', models.BooleanField()),
                ('rss_longitudinal_score', models.FloatField()),
                ('rss_lateral_score', models.FloatField()),
                ('em_path_heading', models.FloatField()),
                ('heading_vs_em_path', models.FloatField()),
                ('em_vt', models.FloatField()),
                ('vt_towards_em_path', models.FloatField()),
                ('em_vm', models.FloatField()),
                ('em_m', models.FloatField()),
                ('em_abs_t', models.FloatField()),
                ('em_signed_t', models.FloatField()),
                ('em_perc_of_seg', models.FloatField()),
                ('min_proj_dist_to_em_seg_edge', models.FloatField()),
                ('added_cutin_path', models.BooleanField()),
                ('rss_lat_safe', models.BooleanField()),
                ('current_rss_lat_safe', models.BooleanField()),
                ('safe_lat_dist', models.FloatField()),
                ('t_braking_dist_lat_brake', models.FloatField()),
                ('em_t_at_lateral_brake_lat', models.FloatField()),
                ('lat_brake_rss_lat_safe', models.BooleanField()),
                ('rss_lat_safe_lat_brake', models.BooleanField()),
                ('speed_based_heading', models.FloatField()),
                ('current_rss_lat_score', models.FloatField()),
                ('lat_brake_rss_lat_score', models.FloatField()),
                ('current_rss_lat_diff', models.FloatField()),
                ('lat_brake_rss_lat_diff', models.FloatField()),
                ('control_on', models.FloatField()),
                ('GFIEndFrame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_endframe', to='hil_app.frame')),
                ('GFIStartFrame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_startframe', to='hil_app.frame')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hil_app.frame', to_field='clip')),
                ('version_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hil_app.version')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineInterventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('GFIEndFrame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_endframe', to='hil_app.frame')),
                ('GFIStartFrame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_startframe', to='hil_app.frame')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hil_app.frame', to_field='clip')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('screenshot_image', models.ImageField(upload_to='contact_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
