# Generated by Django 4.2.4 on 2023-08-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hil_app', '0004_clip_frame_version_userprofile_rssunsafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hil_app.clip'),
        ),
        migrations.AlterField(
            model_name='onlineinterventions',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hil_app.clip'),
        ),
        migrations.AlterField(
            model_name='rssunsafe',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hil_app.clip'),
        ),
    ]
