# Generated by Django 4.2.4 on 2023-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hil_app', '0005_alter_frame_clip_alter_onlineinterventions_clip_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('clip', 'gfi')},
        ),
    ]
