# Generated by Django 4.2.4 on 2023-08-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hil_app', '0006_alter_frame_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rssunsafe',
            old_name='version_name',
            new_name='version',
        ),
    ]
