# Generated by Django 4.2.4 on 2023-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hil_app', '0007_rename_version_name_rssunsafe_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='clip',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='drive_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rssunsafe',
            name='trackfile',
            field=models.CharField(max_length=100),
        ),
    ]
