# Generated by Django 4.2.4 on 2023-09-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hil_app', '0008_alter_clip_clip_alter_clip_drive_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssunsafe',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rssunsafe',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
